src/users/models.py
from os.path import abspath, dirname, join
from datetime import date as dt

import pony.orm as pony
from pony.orm.ormtypes import date

basedir = abspath(dirname(dirname(dirname(__file__))))
PONY_DATABASE_URI = join(basedir, 'users.db')

database = pony.Database(
    "sqlite",
    PONY_DATABASE_URI,
    create_db=True
)


class User(database.Entity):
    username = pony.Required(str, unique=True)
    email = pony.Required(str, 40, unique=True)
    age = pony.Required(int, min=1, max=99)
    phone = pony.Required(str)
    location = pony.Required(str)
    updated_at = pony.Required(date, default=lambda: dt.today())

    def __repr__(self):
        return '{}: {}'.format(self.id, self.username)


class Person(database.Entity):
    """Person, it's asociated with the persons_page"""
    name = pony.Required(str, unique=True)
    city = pony.Required(str)
    phone = pony.Required(str)

    def __repr__(self):
        return '{}: {}'.format(self.id, self.name)

pony.sql_debug(True)

database.generate_mapping(create_tables=True)

src/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField
from wtforms.validators import DataRequired, Email, Length, NumberRange


class UserForm(FlaskForm):
    username = StringField('Name', validators=[DataRequired(), Length(min=-1, max=20, message='You can not have more than 20 characters')])
    email = StringField('E-mail', validators=[Email(), Length(min=-1, max=80, message='You can not have more than 80 characters')])
    age = IntegerField('Age', validators=[NumberRange(min=-1, max=99, message='Age must be a positive integer lower than 99')])
    phone = StringField('Phone', validators=[NumberRange(min=-1, message='Phone can not have more than 20 characters')])
    location = StringField('Location', validators=[Length(min=-1, max=80, message='Location can not have more than 80 characters')])

src/users/__init__.py
from flask import Blueprint
#
# users_page = Blueprint('users_page', __name__, template_folder='templates', url_prefix='/persons')
# users_api = Blueprint('users_api', __name__, url_prefix='/v1/persons')

src/users/views.py
from flask import request, render_template, abort, flash, redirect, url_for, Blueprint
from pony.orm import db_session

from src import app
from src.users.forms import UserForm
from src.users.models import User


users_page = Blueprint('users_page', __name__, url_prefix='/users')


@users_page.route('/', methods=['GET'])
@db_session
def users():
    users = User.select().order_by(User.updated_at)
    return render_template('users/users.html', users=users)


@users_page.route('/search', methods=['GET'])
@db_session
def search():
    search_name = request.args.get('keyword', '')
    users = User.select(lambda u: search_name in u.username)
    return render_template('users/users.html', users=users)


@users_page.route('/create', methods=['GET', 'POST'])
@db_session
def create_user():
    form = UserForm()
    if form.validate_on_submit():
        user = User(username=form.username.data,
                    email=form.email.data,
                    age=form.age.data,
                    phone=form.phone.data,
                    location=form.location.data
                    )
        try:
            app.logger.info('User "{}" created successfully'.format(user.username))
            flash('User created successfully', 'success')
            return redirect(url_for('users_page.users'))
        except Exception as err:
            app.logger.warning('There was an error trying to create an user: {}'.format(repr(err)))
            flash('Error creating user.', 'danger')

    return render_template('users/create_user.html', form=form)


@users_page.route('/delete', methods=['POST'])
@db_session
def delete_user():
    try:
        user_id = request.form['user_id']
        user = User[user_id]
        user_id, username = user.id, user.username
        user.delete()
        app.logger.info('User "{}:{}" deleted successfully'.format(user_id, username))
        flash('User deleted successfully.', 'success')
    except Exception as err:
        app.logger.warning('There was an error trying to delete an user ID: {}'.format(repr(err)))
        flash('Error deleting  user.', 'danger')
    return redirect(url_for('users_page.users'))


@users_page.route('/update/<int:user_id>', methods=['GET', 'POST'])
@db_session
def update_user(user_id):
    user = User.get(id=user_id)
    if not user:
        abort(404)
    form = UserForm(obj=user)
    if form.validate_on_submit():
        try:
            form.populate_obj(user)
            user = user
            app.logger.info('User "{}" updated successfully'.format(user.username))
            flash('Saved successfully', 'success')
        except Exception as err:
            app.logger.warning('There was an error trying to update the user "{}": {}'.format(user.username, repr(err)))
            flash('Error when editing user.', 'danger')
    return render_template('users/edit_user.html', form=form)


# Error handling
@users_page.errorhandler(404)
def not_found(error):
    app.logger.error('There was an 404 error: {}'.format(error))
    return render_template('users/404.html'), 404


@users_page.errorhandler(500)
def internal_error(error):
    app.logger.error('There was an 500 error: {}'.format(error))
    return render_template('users/500.html'), 500


@users_page.route('/dt/', methods=['GET'])
def dt():
    return render_template('users/easteregg.html')

src/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>{% block title %}{% endblock %}</title>

	<link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700" rel="stylesheet">

	<link href="{{ url_for('static', filename='users/css/font-awesome.min.css') }}" rel="stylesheet">

	<link href="{{ url_for('static', filename='users/css/normalize.css') }}" rel="stylesheet">

	<link href="{{ url_for('static', filename='users/css/milligram.min.css') }}" rel="stylesheet">

	<link href="{{ url_for('static', filename='users/css/styles.css') }}" rel="stylesheet">
</head>

<body>
	<div class="navbar">
        <form action="{{ url_for('users_page.search') }}" method="get">
            <div class="row">
                <div class="column column-33 col-site-title"><a href="{{ url_for('users_page.users') }}" class="site-title float-left">Users</a></div>
                    <div class="column column-40 col-search">
                        <input type="text" name="keyword" placeholder="Search..." />
                        <button type="submit" class="btn btn-default fa fa-search" id="search_button"></button>
                    </div>
                    <div id="create" class="column column-33">
                        <a href="{{ url_for('users_page.create_user') }}">New User</a>
                    </div>
            </div>
        </form>
	</div>


    <div class="row">
		<section id="main-content" class="column">

        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert background-{{ category }}">{{ message }}</div>
                {% endfor %}
            {% endif %}
        {% endwith %}

{% block content %}
{% endblock %}
    </section>
</div>

<p class="credit">Template by <a href="https://www.medialoot.com">Medialoot</a></p>


<script src="{{ url_for('static', filename='users/js/chart.min.js') }}"></script>
<script src="{{ url_for('static', filename='users/js/chart-data.js') }}"></script>
</body>
</html>

src/templates/users/create_user.html
{% extends "users/base.html" %}

{% block title %}Edit User {% endblock title %}

{% block content %}
    <div class="row grid-responsive">
        <div class="column column-30">
            <div class="card edit-card">
                <div class="card-title">
                    <h3>New User</h3>
                </div>
                <div class="card-block">
                    <form method="post" action="{{ url_for('users_page.create_user') }}">{{ form.csrf_token }}
                        <fieldset id="edit-user">
                            <div class="form-group">
                                {{ form.username.label }}
                                {{ form.username(size=32) }}
                            {% for error in form.username.errors %}
                            <span style="color: red;">[{{ error }}]</span>
                            {% endfor %}
                            </div>

                            <div class="form-group">
                            {{ form.email.label }}
                            {{ form.email }}
                            {% for error in form.email.errors %}
                            <span style="color: red;">[{{ error }}]</span>
                            {% endfor %}
                            </div>

                            <div class="form-group">
                            {{ form.age.label }}
                            {{ form.age }}
                            {% for error in form.age.errors %}
                            <span style="color: red;">[{{ error }}]</span>
                            {% endfor %}
                            </div>

                            <div class="form-group">
                            {{ form.phone.label }}
                            {{ form.phone }}
                            {% for error in form.phone.errors %}
                            <span style="color: red;">[{{ error }}]</span>
                            {% endfor %}
                            </div>

                            <div class="form-group">
                            {{ form.location.label }}
                            {{ form.location }}<br>
                            {% for error in form.location.errors %}
                            <span style="color: red;">[{{ error }}]</span>
                            {% endfor %}
                            </div><br>

                            <input class="button-primary" type="submit" value="Save">
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/templates/users/easteregg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Easter egg</title>
    <script src="{{ url_for('static', filename='persons/bower_components/jquery/dist/jquery.min.js') }}"></script>

    <style media="screen" type="text/css">
        .center {
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
        .btn {
            background-color:#599bb3;
            -moz-border-radius:28px;
            -webkit-border-radius:28px;
            border-radius:28px;
            border:1px solid #29668f;
            cursor:pointer;
            color:#ffffff;
            font-size:10px;
            font-weight:bold;
            padding:7px 35px;
            text-decoration:none;
            text-shadow:0px 1px 0px #3d768a;
}
    </style>
</head>
<body style="background: black">
    <img class="center" src="{{ url_for('static', filename='users/img/dt.jpg') }}">

    <input type="text" class="center" id="name" placeholder="Type your name...">
    <input type="button" class="btn center" id="submit" value="Enter">

<script type="text/javascript">
    $('#submit').click(function (e) {
        var name = $('#name').val();

        if(name){
            var url = "https://api.whatdoestrumpthink.com/api/v1/quotes/personalized?q="+name;

            $.get(url, function( data ) {
                alert(data.message);
                });
        }
    });
</script>
</body>
</html>

src/templates/users/edit_user.html
{% extends "users/base.html" %}

{% block title %}Edit User {% endblock title %}

{% block content %}
    <div class="row grid-responsive">
        <div class="column column-30">
            <div class="card edit-card">
                <div class="card-title">
                    <h3>Edit User</h3>
                </div>
                <div class="card-block">
                    <form method="post">{{ form.csrf_token }}
                        <fieldset id="edit-user">
                            <div class="form-group">
                                {{ form.username.label }}
                                {{ form.username(size=32) }}
                            {% for error in form.username.errors %}
                            <span style="color: red;">[{{ error }}]</span>
                            {% endfor %}
                            </div>

                            <div class="form-group">
                            {{ form.email.label }}
                            {{ form.email }}
                            {% for error in form.email.errors %}
                            <span style="color: red;">[{{ error }}]</span>
                            {% endfor %}
                            </div>

                            <div class="form-group">
                            {{ form.age.label }}
                            {{ form.age }}
                            {% for error in form.age.errors %}
                            <span style="color: red;">[{{ error }}]</span>
                            {% endfor %}
                            </div>

                            <div class="form-group">
                            {{ form.phone.label }}
                            {{ form.phone }}
                            {% for error in form.phone.errors %}
                            <span style="color: red;">[{{ error }}]</span>
                            {% endfor %}
                            </div>

                            <div class="form-group">
                            {{ form.location.label }}
                            {{ form.location }}<br>
                            {% for error in form.location.errors %}
                            <span style="color: red;">[{{ error }}]</span>
                            {% endfor %}
                            </div><br>

                            <input class="button-primary" type="submit" value="Save">
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/templates/users/users.html
{% extends "users/base.html" %}

{% block content %}
    <div class="row grid-responsive column-offset-25">
        <div class="column">
            <div class="card">
                <div class="card-title">
                    <h3>Users</h3>
                </div>
                <div class="card-block">
                    <table>
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Username</th>
                                <th>Email</th>
                                <th>Age</th>
                                <th>Phone</th>
                                <th>Location</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for user in users %}
                            <tr>
                                <td>{{ user.id }}</td>
                                <td>{{ user.username }}</td>
                                <td>{{ user.email }}</td>
                                <td>{{ user.age }}</td>
                                <td>{{ user.phone }}</td>
                                <td>{{ user.location }}</td>
                                <td align="middle">
                                    <div class="row">
                                        <a class="button button-outline" href="{{ url_for('users_page.update_user', user_id=user.id) }}">Edit</a>
                                        <form action="{{ url_for('users_page.delete_user') }}" method="post">
                                            <input type="hidden" name="user_id" value="{{ user.id }}">
                                            <button type="submit" class="button button-delete">Delete</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        {% else %}
                            </tbody>
                            </table>
                            <h3 class="text-center">No users found <i class="fa fa-frown-o"></i></h3>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}