src/persons/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectMultipleField, DateField, IntegerField
from wtforms.validators import DataRequired, Length


class PartyForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(min=-1, max=20, message='You can not have more than 20 characters')])
    location = StringField('Location', validators=[Length(min=-1, max=80, message='Location can not have more than 80 characters')])
    date = DateField('Date')
    guests = SelectMultipleField('Guests')

src/persons/views.py
from flask import request, render_template, redirect, url_for, Blueprint, jsonify
from pony.orm import db_session
from pony.orm.serialization import to_dict
from pony.orm.core import ObjectNotFound

from src import app

from src.users.models import Person


persons_page = Blueprint('persons_page', __name__, url_prefix='/persons')


@persons_page.route('/', methods=['GET'])
@db_session
def persons():
    persons = Person.select()
    return render_template('persons/persons.html', persons=persons)


@persons_page.route('/person/<int:person_id>', methods=['GET'])
@db_session
def person(person_id):
    try:
        person = Person[person_id]
        person = to_dict(person)
    except ObjectNotFound:
        msg = 'Person ID {} not found'.format(person_id)
        app.logger.info(msg)
        return jsonify(dict(detail=msg)), 404
    return jsonify(person), 200


@persons_page.route('/search-person', methods=['GET'])
@db_session
def search_person():
    search_name = request.args.get('q_person', '')
    persons = Person.select(lambda g: search_name in g.name)
    return render_template('persons/persons.html', persons=persons)


@persons_page.route('/create', methods=['POST'])
def create_person():
    data = request.get_json()
    try:
        with db_session:
            person = Person(name=data.get('name'),
                            city=data.get('city'),
                            phone=data.get('phone'))
    except Exception as err:
        app.logger.info('There was an error trying to create a person: {}'.format(repr(err)))
        return jsonify(status='ko'), 404
    person = to_dict(person)
    app.logger.info('Person created successfully: {}'.format(person))
    return jsonify(person), 201


@persons_page.route('/<int:person_id>', methods=['PUT'])
@db_session
def update_person(person_id):
    data = request.get_json()
    try:
        person = Person[person_id]
    except Exception as err:
        app.logger.info('There was an eror updating person ID {}: {}'.format(person_id, repr(err)))
        return jsonify(status='ko'), 404
    person.name = data.get('name')
    person.city = data.get('city')
    person.phone = data.get('phone')
    return jsonify(status='ok'), 200


@persons_page.route("/delete/<int:person_id>", methods=['GET'])
@db_session
def delete_person(person_id):
    try:
        person = Person[person_id]
        person_id, person_name = person.id, person.name
        person.delete()
        app.logger.info('Person "{}:{}" deleted successfully'.format(person_id, person_name))
    except Exception as err:
        app.logger.warning('There was an error trying to delete a person: {}'.format(repr(err)))
    return redirect(url_for('persons_page.persons'))

src/templates/persons/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}{% endblock %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

<script src="{{ url_for('static', filename='persons/bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ url_for('static', filename='persons/bower_components/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ url_for('static', filename='persons/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{{ url_for('static', filename='persons/bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='persons/dist/css/custom.css') }}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ url_for('static', filename='persons/bower_components/font-awesome/css/font-awesome.min.css') }}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{{ url_for('static', filename='persons/bower_components/Ionicons/css/ionicons.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ url_for('static', filename='persons/dist/css/AdminLTE.min.css') }}">
  <!-- AdminLTE Skins -->
  <link rel="stylesheet" href="{{ url_for('static', filename='persons/dist/css/skins/_all-skins.min.css') }}">

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
<header class="main-header">
    <!-- Logo -->
    <a href="{{ url_for('persons_page.persons') }}" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg">Persons</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <div class="navbar-custom-menu">
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <section class="sidebar">
      <ul class="sidebar-menu" data-widget="tree">
        <li>
          <a href="{{ url_for('persons_page.persons') }}">
            <i class="fa fa-users"></i> <span>Persons</span>
          </a>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1><a href="{{ url_for('persons_page.persons') }}">Dashboard</a></h1>
      <ol class="breadcrumb">
        <li><a href="{{ url_for('persons_page.persons') }}"><i class="fa fa-dashboard"></i> Home</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">


{% block content %}
{% endblock %}


       </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.4.0
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
    reserved.
  </footer>
</div>
<!-- ./wrapper -->


<!-- jQuery 3 -->
<script src="{{ url_for('static', filename='persons/bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ url_for('static', filename='persons/bower_components/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ url_for('static', filename='persons/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
{#<!-- daterangepicker -->#}
<script src="{{ url_for('static', filename='persons/bower_components/moment/min/moment.min.js') }}"></script>
<!-- datepicker -->
<script src="{{ url_for('static', filename='persons/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ url_for('static', filename='persons/dist/js/adminlte.min.js') }}"></script>
</body>
</html>

src/templates/persons/persons.html
{% extends 'persons/base.html' %}

{% block title %}Persons {% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header">
            <h3 class="box-title" title="Refresh table"><a href="{{ url_for('persons_page.persons') }}">Persons</a></h3>

          <div class="box-tools create-person">
              <button type="button" class="btn btn-block btn-info" onclick="generatePerson()">Generate person </button>
          </div>
          <div class="box-tools">
            <form action="{{ url_for('persons_page.search_person') }}" method="get">
                <div class="input-group input-group-sm" style="width: 150px;">
                      <input type="text" name="q_person" class="form-control pull-right" placeholder="Search...">

                      <div class="input-group-btn">
                        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                      </div>
                </div>
            </form>
          </div>
        </div>
        <div class="box-body table-responsive no-padding">
          <table class="table table-hover custom-hoover">
            <thead>
                <tr>
                  <th>ID</th>
                  <th>Name</th>
                  <th>City</th>
                  <th>Phone</th>
                </tr>
            <thead>
            <tbody>
              {% for person in persons %}
                <tr data-toggle="modal" data-target="#modal-party" data-id="{{ person.id }}">
                  <td>{{ person.id }}</td>
                  <td>{{ person.name }}</td>
                  <td>{{ person.city }}</td>
                  <td>{{ person.phone }}</td>
                </tr>
              {% endfor %}
            <tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

    {#  MODAL  #}
    <div class="modal fade" id="modal-party">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Edit person</h4>
          </div>
            <form method="">
              <div class="modal-body">
                <div class="form-group">
                  <label for="person_id">ID</label>
                  <input type="text" class="form-control" id="id" placeholder="ID" readonly>
                </div>
                <div class="form-group">
                  <label for="person_name">Name</label>
                  <input type="text" class="form-control" id="name" placeholder="Name">
                </div>
                <div class="form-group">
                  <label for="person_city">City</label>
                  <input type="text" class="form-control" id="city" placeholder="City">
                </div>
                <div class="form-group">
                  <label for="person_phone">Phone</label>
                  <input type="text" class="form-control" id="phone" placeholder="Phone">
                </div>
              </div>

              <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal" id="close_modal">Close</button>
                <button type="button" class="btn btn-danger" onclick="deletePerson();">Delete</button>
                <button type="button" class="btn btn-primary" id="save">Save changes</button>
              </div>
            </form>
        </div>
      </div>
    </div>



    <script type="text/javascript">
        function generatePerson(){
            var ulrRandomApi = "https://randomuser.me/api/";
            var postData = null;
            $.ajax({
                  url: ulrRandomApi,
                  dataType: 'json',
                  success: function(data) {
                      var results = data.results[0];
                      postData = {
                          name: results.name.first,
                          city: results.location.city,
                          phone: results.phone
                      };
                      var urlPOST = "{{ url_for('persons_page.create_person') }}";
                      $.ajax({
                          type: "POST",
                          url: urlPOST,
                          contentType: 'application/json',
                          dataType: 'json',
                          data: JSON.stringify(postData),
                          success: function(data) {
                            location.reload();
                          }
                        });
                  }
                });
        }

        $("table tbody > tr").click(function() {
            var personID = $(event.target).closest('tr').data('id');
            $.ajax({
                  url: "/persons/person/"+personID,
                  success:function(data) {
                      var party_data = data.Person[personID];
                      $("#id").val(personID);
                      $("#name").val(party_data.name);
                      $("#city").val(party_data.city);
                      $("#phone").val(party_data.phone);
                  },
                  error: function(errorThrown){
                        {# Handle error#}
                      console.log(errorThrown);
                      }
                 });
        });

        $('#save').click(function (e) {
            var personID = $("#id").val();
            var putData = {
                  name: $("#name").val(),
                  city: $("#city").val(),
                  phone: $("#phone").val()
            };

            var url = "/persons/"+personID;
            $.ajax({
                type: "PUT",
                url: url,
                contentType: 'application/json',
                dataType: 'json',
                data: JSON.stringify(putData),
                success: function (data) {
                  location.reload();
                }
            });
        });

        function deletePerson() {
        var personID = $("#id").val();
        if(!personID) return;

         $.ajax({
              url: '/persons/delete/'+personID,
              success:function(response) {
                  $("#close_modal").click();
                  location.reload();
              },
              error: function(errorThrown){
                  console.log(errorThrown);
                  }
             });
        }
    </script>
{% endblock %}